import:
  from_scratch: yes
  timid: yes
replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '^\s+': ''
  '^-': _
  '’': "'"
  '[“”]': '"'
musicbrainz:
  genre: yes
plugins: bandcamp chroma discogs edit fetchart fromfilename fuzzy info mbsync missing mpdupdate scrub spotify zero
discogs:
  source_weight: 0.5
bandcamp:
  source_weight: 0.6
spotify:
  source_weight: 0.0
fuzzy:
  prefix: "@"
zero:
  fields: images
  update_database: true